getting started (#1)
* example1

* force fail

* fake buildtest workflow

* a more interesting config

* indentation

* ok maybe i need this space

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -1,13 +1,35 @@
-# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
-version: 2.1
-# Use a package of configuration called an orb.
-orbs:
-  # Declare a dependency on the welcome-orb
-  welcome: circleci/welcome-orb@0.4.1
-# Orchestrate or schedule a set of jobs
+ # Use the first example from https://circleci.com/docs/2.0/getting-started/
+version: 2
+jobs:
+  build:
+    docker:
+      - image: circleci/ruby:2.4.1
+    steps:
+      - checkout
+      - run: mkdir -p src
+      - run: echo "hello world, again" > src/hello
+      - persist_to_workspace:
+          root: src
+          paths:
+            - hello
+  test:
+    docker:
+      - image: circleci/ruby:2.4.1
+    steps:
+      - checkout
+      - attach_workspace:
+          at: src
+      - run: |
+          if [[ $(cat src/hello) == "hello world, again" ]]; then
+            echo "woo";
+          else
+            echo "fi ends if, amazing. also you failed"; exit 123
+          fi
 workflows:
-  # Name the workflow "welcome"
-  welcome:
-    # Run the welcome/run job in its own container
+  version: 2
+  build_and_test:
     jobs:
-      - welcome/run
+      - build
+      - test:
+          requires:
+            - build
