a more interesting config

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -6,16 +6,30 @@ jobs:
       - image: circleci/ruby:2.4.1
     steps:
       - checkout
-      - run: echo "nothing to build"
+      - run: mkdir -p src
+      - run: echo "hello world, again" > src/hello
+      - persist_to_workspace:
+          root: src
+          paths:
+            - hello
   test:
     docker:
       - image: circleci/ruby:2.4.1
     steps:
       - checkout
-      - run: echo "nothing to test"
+      - attach_workspace:
+        at: src
+      - run: |
+          if [[ $(cat src/hello) == "hello world, again"]]; then
+            echo "woo";
+          else
+            echo "fi ends if, amazing. also you failed"; exit 123
+          fi
 workflows:
   version: 2
   build_and_test:
     jobs:
       - build
-      - test
+      - test:
+          requires:
+            - build
